---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: desk
# description will be included in the image's metadata
description: https://github.com/perchnet/desk

# the base image to build on top of (FROM) and the version tag to use
# base-image: ghcr.io/ublue-os/silverblue-main
#base-image: ghcr.io/ublue-os/cosmic-kinoite
#base-image: ghcr.io/ublue-os/bluefin-dx
base-image: ghcr.io/zirconium-dev/zirconium
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: script
    scripts:
      - "before-packages.sh"
  - type: script
    snippets:
      - "dnf install --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release -y"
  - type: dnf
    repos:
      cleanup: true
      copr:
        - ublue-os/staging
        - ublue-os/packages
        - scottames/ghostty
        - brirec/interception-tools
        - deltacopy/darkly
        - atim/starship
      files:
        - https://pkgs.tailscale.com/unstable/fedora/tailscale.repo
        - https://packages.microsoft.com/yumrepos/edge/config.repo
        #- https://packages.microsoft.com/yumrepos/vscode/config.repo

    install:
      packages:
        #- repo: copr:copr.fedorainfracloud.org:scottames:ghostty
        #  packages:
        #    - ghostty
        - repo: copr:copr.fedorainfracloud.org:brirec:interception-tools
          packages:
            - interception-tools
        - repo: copr:copr.fedorainfracloud.org:atim:starship
          packages:
            - starship
        - repo: terra
          packages:
            - zed
        - chromium
        - dialog
        - elementary-files
        - falkon
        - libevdev-devel
        - idevicerestore
        - microsoft-edge-beta
        - microsoft-edge-stable
        - neovim
        - podlet
        - waypipe
        - xeyes
        - yaml-cpp
        - yaml-cpp-devel
        - zsh
        - zoxide
        - https://downloads.1password.com/linux/rpm/edge/x86_64/1password-latest.rpm
        - https://downloads.1password.com/linux/rpm/edge/x86_64/1password-cli-latest.x86_64.rpm
        - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        - https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
        - https://github.com/peazip/PeaZip/releases/download/10.5.0/peazip-10.5.0.LINUX.Qt6-1.x86_64.rpm
        - https://prerelease.keybase.io/keybase_amd64.rpm
        - https://vivaldi.com/download/vivaldi-stable.x86_64.rpm
        - https://github.com/xpipe-io/xpipe/releases/latest/download/xpipe-installer-linux-x86_64.rpm
        - https://github.com/xpipe-io/xpipe-ptb/releases/latest/download/xpipe-installer-linux-x86_64.rpm
        - https://code.visualstudio.com/sha/download?build=stable&os=linux-rpm-x64
    replace:
      - from-repo: tailscale-unstable
        packages:
          - tailscale
        install-weak-deps: true
        skip-unavailable: false
        skip-broken: false
        allow-erasing: false
    group-install:
      packages:
        - cosmic-desktop
        - cosmic-desktop-apps
      with-optional: true
      install-weak-deps: true
      skip-unavailable: false
      skip-broken: false
      allow-erasing: false
  - type: dnf
    install:
      skip-broken: true
      packages:
        - repo: copr:copr.fedorainfracloud.org:deltacopy:darkly
          packages:
            - darkly

  - type: script
    snippets:
      - "rm /etc/yum.repos.d/teamviewer.repo" # because its signing is broken and i'm baking the rpm in anyway...
  - type: script
    snippets:
      - "mkdir -p /tmp/"
  - type: files
    files:
      - source: data
        destination: /tmp/
  - type: script
    scripts:
      - "winbox.sh"
      - "install_cursor_ai.sh"
      - "install-1p.sh"
      # - "keymapper.sh"

  - type: default-flatpaks@v1
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        # - org.mozilla.firefox
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: bin-wrapper
    source: ghcr.io/perchnet/modules/bin-wrapper
    bin: /usr/bin/code
    flags:
      - --ozone-platform-hint=auto
  - type: bin-wrapper
    source: ghcr.io/perchnet/modules/bin-wrapper
    bin: /usr/bin/microsoft-edge-beta
    flags:
      - --ozone-platform-hint=auto
      - --enable-features=UseOzonePlatform,TouchpadOverscrollHistoryNavigation
  - type: bin-wrapper
    source: ghcr.io/perchnet/modules/bin-wrapper
    bin: /usr/bin/microsoft-edge-stable
    flags:
      - --ozone-platform-hint=auto
      - --enable-features=UseOzonePlatform,TouchpadOverscrollHistoryNavigation
  - type: bin-wrapper
    source: ghcr.io/perchnet/modules/bin-wrapper
    bin: /usr/bin/microsoft-edge-dev
    flags:
      - --ozone-platform-hint=auto
      - --enable-features=UseOzonePlatform,TouchpadOverscrollHistoryNavigation
  - type: bin-wrapper
    source: ghcr.io/perchnet/modules/bin-wrapper
    bin: /usr/bin/microsoft-edge-canary
    flags:
      - --ozone-platform-hint=auto
      - --enable-features=UseOzonePlatform,TouchpadOverscrollHistoryNavigation

  - type: bin-wrapper
    source: ghcr.io/perchnet/modules/bin-wrapper
    bin: /usr/bin/cursor
    flags:
      - --ozone-platform-hint=auto
      - --enable-features=UseOzonePlatform
      - --no-sandbox

  - type: bin-wrapper
    source: ghcr.io/perchnet/modules/bin-wrapper
    bin: /usr/bin/windsurf
    flags:
      - --ozone-platform-hint=auto
      - --enable-features=UseOzonePlatform
      - --no-sandbox

  - type: bling
    install:
      # - ublue-update # https://github.com/ublue-os/ublue-update
      #- 1password # install 1Password (stable) and `op` CLI tool
      - dconf-update-service # a service unit that updates the dconf db on boot

  - type: bin-wrapper
    source: ghcr.io/perchnet/modules/bin-wrapper
    bin: /usr/lib/1Password/1password
    flags:
      - --ozone-platform-hint=auto
      - --enable-features=UseOzonePlatform

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  #- type: script
  #  snippets:
  #    - |
  #      mv /usr/lib/opt /usr/lib/bluebuild-optfix
  #      ln -s /usr/lib/bluebuild-optfix /usr/lib/opt

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
