---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: desk
# description will be included in the image's metadata
description: https://github.com/perchnet/desk

# the base image to build on top of (FROM) and the version tag to use
# base-image: ghcr.io/ublue-os/silverblue-main
#base-image: ghcr.io/ublue-os/cosmic-kinoite
#base-image: ghcr.io/ublue-os/bluefin-dx
base-image: ghcr.io/zirconium-dev/zirconium
#base-image: ghcr.io/perchnet/zirconium
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: includes/10-installs.yml
  - from-file: includes/20-scripts.yml
  - from-file: includes/30-default-flatpaks.yml
  - from-file: includes/40-bin-wrappers.yml
  - from-file: includes/50-bling.yml
  - from-file: includes/60-files.yml
  #- from-file: includes/70-zdots-override.yml
  - from-file: includes/80-theming.yml
  - from-file: includes/99-test-shit.yml
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
