---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: desk
# description will be included in the image's metadata
description: https://github.com/perchnet/desk

# the base image to build on top of (FROM) and the version tag to use
# base-image: ghcr.io/ublue-os/silverblue-main
#base-image: ghcr.io/ublue-os/cosmic-kinoite
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: script
    scripts:
      - "before-packages.sh"
  - type: dnf
    repos:
      files:
        - https://packages.microsoft.com/yumrepos/edge/config.repo
        #- https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/yum/windsurf.repo
      copr:
        - brirec/interception-tools
        #- ryanabx/cosmic-epoch
        - pgdev/ghostty
        - che/nerd-fonts
        - deltacopy/darkly
        - atim/starship
      cleanup: true
    group-install:
      with-optional: true
      packages:
        - cosmic-desktop
        - cosmic-desktop-apps
    install:
      packages:
        - chromium
        - darkly
        - dialog
        - elementary-files
        - falkon
        - ghostty
        - interception-tools
        - libevdev-devel
        - microsoft-edge-beta
        - microsoft-edge-stable
        - neovim
        - podlet
        - steam
        - waypipe
        #- windsurf
        - xeyes
        - yaml-cpp
        - yaml-cpp-devel
        - zed
        - zoxide
        - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        - https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
        - https://github.com/peazip/PeaZip/releases/download/10.5.0/peazip-10.5.0.LINUX.Qt6-1.x86_64.rpm
        - https://prerelease.keybase.io/keybase_amd64.rpm
        - https://vivaldi.com/download/vivaldi-stable.x86_64.rpm
    #remove: [ "xwaylandvideobridge" ]
    optfix:
      - google
      - keybase
      - microsoft
      - teamviewer
      - vivaldi
      # https://blue-build.org/reference/modules/rpm-ostree/#optfix-optional-array
  - type: script
    snippets:
      - "rm /etc/yum.repos.d/teamviewer.repo" # because its signing is broken and i'm baking the rpm in anyway...
  - type: script
    scripts:
      - "winbox.sh"
      - "install_cursor_ai.sh"
      # - "keymapper.sh"

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        # - org.mozilla.firefox
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: bin-wrapper
    source: ghcr.io/perchnet/modules/bin-wrapper
    bin: /usr/bin/code
    flags:
      - --ozone-platform-hint=auto
  - type: bin-wrapper
    source: ghcr.io/perchnet/modules/bin-wrapper
    bin: /usr/bin/microsoft-edge-beta
    flags:
      - --ozone-platform-hint=auto
      - --enable-features=UseOzonePlatform,TouchpadOverscrollHistoryNavigation
  - type: bin-wrapper
    source: ghcr.io/perchnet/modules/bin-wrapper
    bin: /usr/bin/microsoft-edge-stable
    flags:
      - --ozone-platform-hint=auto
      - --enable-features=UseOzonePlatform,TouchpadOverscrollHistoryNavigation
  - type: bin-wrapper
    source: ghcr.io/perchnet/modules/bin-wrapper
    bin: /usr/bin/microsoft-edge-dev
    flags:
      - --ozone-platform-hint=auto
      - --enable-features=UseOzonePlatform,TouchpadOverscrollHistoryNavigation
  - type: bin-wrapper
    source: ghcr.io/perchnet/modules/bin-wrapper
    bin: /usr/bin/microsoft-edge-canary
    flags:
      - --ozone-platform-hint=auto
      - --enable-features=UseOzonePlatform,TouchpadOverscrollHistoryNavigation

  - type: bin-wrapper
    source: ghcr.io/perchnet/modules/bin-wrapper
    bin: /usr/bin/cursor
    flags:
      - --ozone-platform-hint=auto
      - --enable-features=UseOzonePlatform
      - --no-sandbox

  - type: bin-wrapper
    source: ghcr.io/perchnet/modules/bin-wrapper
    bin: /usr/bin/windsurf
    flags:
      - --ozone-platform-hint=auto
      - --enable-features=UseOzonePlatform
      - --no-sandbox

  - type: bling
    install:
      # - ublue-update # https://github.com/ublue-os/ublue-update
      - 1password # install 1Password (stable) and `op` CLI tool
      - dconf-update-service # a service unit that updates the dconf db on boot

  - type: bin-wrapper
    source: ghcr.io/perchnet/modules/bin-wrapper
    bin: /usr/lib/1Password/1password
    flags:
      - --ozone-platform-hint=auto
      - --enable-features=UseOzonePlatform

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /


  - type: signing # this sets up the proper policy & signing files for signed images to work fully
